[phases.setup]
nixPkgs = ["python312", "gcc", "pkg-config"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "python app.py"

[variables]
NIXPACKS_PYTHON_ENTRY_POINT = "app.py"
NIXPACKS_NO_CACHE = "1"
